### ISSUE TITLE
How to bring the application to the foreground when the bubble is tapped?

### ISSUE THREAD

**Issue by glennmichaelmejias** [moazelsawaf/dash_bubble#3]
How to bring the application to the foreground when the bubble is tapped?

**Comment by moazelsawaf** [comment]
As I understand it, you want to bring the app to the **foreground** when the bubble is tapped while the app is in the **background** 📲

If that is correct, then you can easily do that with the help of the [flutter_foreground_task](https://pub.dev/packages/flutter_foreground_task) package 💙

You will just need to invoke the following method in your suitable bubble callback, for example `onTap()`:

```Dart
FlutterForegroundTask.launchApp();
```

That's it 👌🏻💙

**Comment by moazelsawaf** [comment]
To detect when an app transitions between the **background** and **foreground**, you can observe the `AppLifecycleState` 📲

For more information on this topic and its implementation, please refer to this [tutorial](https://www.youtube.com/watch?v=JyapvlrmM24) on YouTube ▶

After setting up the observer, you can start your bubble in the callback when the app moves to the background and stop it when the app goes to the foreground ✅

I hope this answers your question 💙

-----------

Additionally, I would like to remind you that this implementation will be built-in available in the feature mentioned in my previous comment ✅

Stay tuned for updates! 💪🏻💙

**Comment by OsamaQureshi796** [comment]
Hi @moazelsawaf 
I'm waiting for the super update please can you let me know how much time it'll take to be available.
Thanks for such awesome work.
