### ISSUE TITLE
App is crashing when it is detached/terminated while running in the background with the bubble also running

### ISSUE THREAD

**Issue by robilin** [moazelsawaf/dash_bubble#4]
I am experiencing an app crash when I close the app while it is **running in the background** and the **bubble is running**.

Do you have any ideas on how to fix this?

**Comment by moazelsawaf** [comment]
Hello @robilin 👋🏻

I have tried to mimic the same scenario you have described but everything is working fine for me ✅

Can you please provide me with a minimal reproduceable code? 🙏🏻
