### ISSUE TITLE
android 9 and android 11 app crashed

### ISSUE THREAD

**Issue by selvam920** [moazelsawaf/dash_bubble#5]
pls check app crashed or hasOverlayPermission or requestOverlayPermission not return true if already persmission given

**Comment by moazelsawaf** [comment]
Hi @selvam920 👋🏻

Do you mean that the application crashes when you try to call `hasOverlayPermission()` or `requestOverlayPermission()` when the permission is **Granted**? Or is something else happening? 🤔

By the way, I have tested the app in **Android 11** against this scenario and everything is working fine and as expected. Both methods returned `true` ✅

Please clarify the issue and provide me with all the details that you can 🙏🏻

It would also be great if you could provide me with a minimal reproducible example to run and test 👌🏻

Thank you for your help 🙏🏻💙

**Comment by selvam920** [comment]
i checked android tv 11 and 9

**Comment by moazelsawaf** [comment]
@selvam920 

Please describe the issue clearly with all the details. I am still unable to understand the issue and the platforms you are facing the issue with ...
