### ISSUE TITLE
Custom screen outside the app

### ISSUE THREAD

**Issue by aminsamad** [moazelsawaf/dash_bubble#6]
I want to after starting the floating button and exit the app click the floating and show me dialog box or other custom screen ? onTap parameter just for print and log there is any way to create my type ?

**Comment by moazelsawaf** [comment]
Hello @aminsamad 👋🏻

Unfortunlly, currently there is no built-in option in the package to show a floating custom view outside the app 😔

But I think this option would be added in the near future Insha'Allah along with other exciting features 💪🏻

Once this option is added, I will inform you immediately in this issue ✅

Until that, feel free to ask me anything or to close the issue 🙏🏻
