### ISSUE TITLE
App crashes when I start Call of Duty game while the bubble is running

### ISSUE THREAD

**Issue by robilin** [moazelsawaf/dash_bubble#9]
I have an app with the package added to it, the app crashes when I start **Call of Duty** game on the mobile while the bubble is running 😔

I think the game is trying to prevent **Drawing on top of other apps** feature because some times similar issues are happening with other apps require permission to run on top of other apps 🤔

📃 Here is the logged exception when the app crashed:

```
FATAL EXCEPTION: main Process: com.paisha.provider, PID: 32430
java.lang.RuntimeException: Unable to create service dev.moaz.dash_bubble.src.BubbleService: com.torrydo.floatingbubbleview.PermissionDeniedException: "display over other app" permission IS NOT granted!
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4953)
at android.app.ActivityThread.access$1800(ActivityThread.java:310)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: com.torrydo.floatingbubbleview.PermissionDeniedException: "display over other app" permission IS NOT granted!
at com.torrydo.floatingbubbleview.FloatingBubbleService.onCreate(FloatingBubbleService.kt:56)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4940)
at android.app.ActivityThread.access$1800(ActivityThread.java:310)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by moazelsawaf** [comment]
I’m sorry to hear that you’re facing difficulties with the issue 😞

Could you please provide more details about what you are trying to implement and the problem you’re experiencing. It would be better if you could provide minimal code and steps to reproduce the issue?

Additionally, please ensure that you have enabled the **Overlay Permission** through `hasOverlayPermission()` method before you start the bubble.

Lastly, could you clarify what do you mean by **while bubble is in background**? Because the bubble is either visible in both foreground and background or fully stopped in both cases, also please clarify when and how do you start the bubble.

**Comment by robilin** [comment]
Am trying to implement ability of an app to run on top of other apps when minimized, or any running in background.

I am using dash_bubble together with foregrpundTask `   
FlutterForegroundTask.launchApp()` am using this in call back so that it is possible to tap floating button to bring the app forward.

Everything works fine, except when the app is in background and bubble icon is running, if i start different app, that runs as well on top of other apps, my whole application crashes. and the error shows bubble logs as indicated.


**while bubble is in background**  this means the main app is minimized and floating icon for bubble is visible, while the rest of the app is in background (the actual overlay mode). 

So the issue happens if i attemp to run anaother app, in this case it can be easily by entering game mode while the app  utlizing bubble is as well running., after few seconds the whole app will crash and in logcat you can see that error.

this is some codes that starts bubble.

`    onWillStart: () async {

          if(Get.find<AuthController>().profileModel.active == 1) {

           final status = _requestPermissionForAndroid();

           if(status != null){

             final isRunning = await DashBubble.instance.isRunning();

             final hasPermission = await DashBubble.instance.hasOverlayPermission();

             if(!isRunning && hasPermission ) {
               _startBubble(
                 context,
                 bubbleOptions: BubbleOptions(
                   // notificationIcon: 'github_bubble',
                   bubbleIcon: 'logo_bubble_icon',
                   // closeIcon: 'github_bubble',
                   startLocationX: 0,
                   startLocationY: 100,
                   bubbleSize: 100,
                   opacity: 1,
                   enableClose: true,
                   closeBehavior: CloseBehavior.following,
                   distanceToClose: 100,
                   enableAnimateToEdge: true,
                   enableBottomShadow: true,
                   keepAliveWhenAppExit: false,
                 ),
                 notificationOptions: NotificationOptions(
                   id: 1,
                   title: 'Paisha',
                   icon: 'notification_icon',
                   body: 'Paisha service is running',
                   channelId: 'dash_bubble_notification',
                   channelName: 'Paisha Notification',
                 ),
                 onTap: () =>
                     openTheApp(
                       context: context,
                     ), //call back on what happens when the button is tapped
               );
             }else{

             }
           }

            // Return whether to start the foreground service.
            if (kDebugMode) {
              print("app is minimized");
            }
            return true;
          }else{
            return false;
          }
        },`

**This is call back frunction**

  void openTheApp({BuildContext context}) {
    FlutterForegroundTask.launchApp();
  }

**Comment by moazelsawaf** [comment]
Thank you for providing these detailed information 🙏🏻

Additionally, could you provide me with a small app/game that has the same conflict? because **Call of Duty** is too large in size, it would also be helpful if you could provide me with the Mobile/Emulator that you are facing the issue with and the Android Version. 

Thank you! 💙

**Comment by robilin** [comment]
Let me check if i can get something that can create same scenerio using different second app, then i will share to you.

**Comment by moazelsawaf** [comment]
Do not worry about that 🙏🏻

I have installed **Call of Duty** on my mobile device, specifically [Call of Duty: Mobile Season 9](https://play.google.com/store/apps/details?id=com.activision.callofduty.shooter&hl=en&gl=US), However, I was unable to replicate the issue. I have tested the game while the bubble is running multiple times and everything worked fine as intended. Therefore, it seems that the problem does not exist on my mobile device ✅

📹 I have recorded this video for my last trial _(The video has been sped up to 2x for faster watching and to reduce the size)_:

https://github.com/moazelsawaf/dash_bubble/assets/43591891/a4db6cc5-c132-415e-9b21-2f3f8e9d50e4

I would appreciate it if you could provide me with additional details to help me reproduce the issue and resolve it as soon as possible. I will be waiting for your response. 🙏🏻

**Comment by robilin** [comment]
Tried to replicate the problem more with call of duty, it happens when you set don't disturb mode for game, this will cause the button not to show up and app crashes after sometime. in three to five minutes
